### ISSUE TITLE
Pl. add semicolon to the end of exports statement.

### ISSUE THREAD

**Issue by vidoss** [jameswomack/modcss#1]
When using the transform with 'hintify' - Its throwing "Missing semicolon" error" . To reproduce...

Copy the example from readme
%npm install hintify
%browserify -t modcss -t hintify ./my-component.js

**Comment by jameswomack** [comment]
I'll look into it @vidoss

**Comment by jameswomack** [comment]
@vidoss Try modcss@1.1.2-alpha and let me know how it goes

**Comment by vidoss** [comment]
works. Thanks.
