### ISSUE TITLE
Pass browserify "paths" to stylus

### ISSUE THREAD

**Issue by vidoss** [jameswomack/modcss#2]
Would like a way to pass the browserify "paths" option to stylus(). This will help make the @import path compact. esp if I have to include styl from other node_modules. browserify passes all its options as _flags in second argument to transformers.

**Comment by jameswomack** [comment]
@vidoss I like the idea. What would you see this looking like in use?

**Comment by vidoss** [comment]
Without passing paths only the current directory of .styl file is passed to the stylus compiler. So if I have to import something from another node_module the import looks something like this...

@import '../../../../../../node_modules/my-stylus-lib/colors.styl'

If I could pass the paths, all the ".." can be removed. It will be...

@import 'my-stylus-lib/colors.styl'

**Comment by jameswomack** [comment]
I got that—I'm aware of the paths functionality in Stylus. What I was
asking is what would you see the implementation as.

On Sat, Sep 19, 2015 at 10:38 PM, Victor Doss <notifications@github.com>
wrote:

> Without passing paths only the current directory of .styl file is passed
> to the stylus compiler. So if I have to import something from another
> node_module the import looks something like this...
>
> @import <https://github.com/import>
> '../../../../../../node_modules/my-stylus-lib/colors.styl'
>
> If I could pass the paths, all the ".." can be removed. It will be...
>
> @import <https://github.com/import> 'my-stylus-lib/colors.styl'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jameswomack/modcss/issues/2#issuecomment-141751413>.
>



-- 
James J. Womack
Senior Software Engineer/Architect
Netflix

**Comment by vidoss** [comment]
The options are passed in as second argument to browserify transform modules. Need to pass that down to the call to stylus compiler.

module.exports = function (filename, opts) {
      var paths = opts.paths || opts._flags.paths ;

**Comment by vidoss** [comment]
Works great. Thanks.
